# Company Information
company_name: Online Academy
domain_name: 
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the Online Academy website.
meta_description: online education, e-learning, primary and secondary school mathematics, CSEC, CXC.

# Site Information
title: Online Academy
author: Desmond Bennett
baseurl: ""
url: #

# Social Links
facebook_link: #
twitter_link: #
github_link: #

disqus: false
disqus_shortname: online_academy

paginate: 20

# Build settings
markdown: kramdown